modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"

[[mods]]
modId = "customcursor"
version = "${version}"
displayName = "${name}"
authors = "Me"
description = "This is an example description! Tell everyone what your mod is about!"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "customcursor-common.mixins.json"

[[mixins]]
config = "customcursor-neoforge.mixins.json"